### ISSUE TITLE
Fonctionne pas la version nouvelle technologic

### ISSUE THREAD

**Issue by totaldebrid** [Clashplayer-PROTECT/sh-fivem#3]
salut apres plusieur teste sa fonctionne pas en tous cas la version nouvelle technologique 

systemctl fivem start

systemctl fivem restart

systemctl fivem stop

systemctl fivem status

reponse avec putty  =  Unknown operation fivem.

pour chaque commande plus haut ??

en plus quand on ferme la console sa éteint  direct le serveur donc  ne sert pas a grand chose a comparer des autre tuto du mème style ?

**Comment by Clashplayer** [comment]
Hello totaldebrid,

Par rapport à la nouvelle technologie quelques fois le systemctl status fivem ne marche. Je vous conseille donc  systemctl start fivem.service etc.

Une astuce si votre serveur reboot automatiquement simplement : systemctl enable fivem.service --now ;)

Encore besoin d'aide join le discord ;)

**Comment by totaldebrid** [comment]
Start & Restart & Stop & Status votre serveur avec la nouvelle technologie !

systemctl restart fivem.service  ne fonctionne pas

merci j'ai tester fonctionne pas j’ai aussi été sur discord poster plusieurs message mais personne répond donc je re tente ici désoler ;) 

systemctl fivem restart  celle la non plus ?

a et aussi pendant l'installe pour le phpmyadmin  tous c'est bien passer mais en ouvrant phpmyadmin y a des erreur donc peut être aussi possibilité de corriger les erreur

question aussi comment utiliser bxadmin avec le tuto pour les vps ? merci

**Comment by Clashplayer** [comment]
C'est quoi ton TAG DISCORD ?
